### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by 15757955216** [pmj110119/RenderOcc#10]
您好，您的工作非常棒！ 当前我尝试复现您的2D GT代码。 使用configs/renderocc/renderocc-7frame.py的默认配置进行训练，但是当前评测第6个epoch模型指标时发现仅有3.04miou，请问这正常吗。 因为我看见您在这个issue中https://github.com/pmj110119/RenderOcc/issues/3 回答称6ep就可以达到24miou，以下是训练log，可以看看有什么问题吗。
[20231018_105834.log](https://github.com/pmj110119/RenderOcc/files/13031085/20231018_105834.log)
或者能否开源您的训练log以便进行对比呢。
<img width="752" alt="屏幕截图 2023-10-19 001331" src="https://github.com/pmj110119/RenderOcc/assets/37320731/b7ca6257-c024-4e77-b1a2-cd49bd303671">
以上是loss收敛曲线，并未见有训练发散。
等训练完12ep后，再跟进评测指标。 感谢！
PS：8 * A100上进行训练，默认配置文件。

**Comment by pmj110119** [comment]
您好，我在readme里更新了训练log链接。

看上去render_depth_loss没有正常收敛，请问depth GT是用我的脚本生成的吗，有没有改动什么

**Comment by 15757955216** [comment]
> 您好，我在readme里更新了训练log链接。
> 
> 看上去render_depth_loss没有正常收敛，请问depth GT是用我的脚本生成的吗，有没有改动什么

您好，感谢回复。depth GT生成脚本用的是源码中的脚本生成的，并没有做改动。 但是配置文件中这个"rays_info" 关键字在数据加载过程中报错，我看dataset的加载代码使用的是“rays”关键字，因此修改为了“rays”, https://github.com/pmj110119/RenderOcc/blob/dd11f18ec533ba7c412a602b7aadde4a155491b6/configs/renderocc/bevstereo-occ.py#L154  . 仅有此处进行了改动，不知是否是这里存在问题。

**Comment by pmj110119** [comment]
不好意思请等我明天排查下QAQ，之前合并了一个pr后没有进行验证，可能是不小心引入了bug。

**Comment by 15757955216** [comment]
> 不好意思请等我明天排查下QAQ，之前合并了一个pr后没有进行验证，可能是不小心引入了bug。

好的，十分感谢。

**Comment by 99er-gao** [comment]
同样的复现情况，插眼。

**Comment by pmj110119** [comment]
把脚本 `tools/dist_train.sh` 的倒数第二行 `--seed 0 \` 去掉，loss看着就正常了（还没训完，等训完出评测结果后我会更新）。

这个随机种子我是从别的repo代码直接复制过来的，不知道为啥加个随机种子模型就不收敛了。有没有大佬解惑一下......

**Comment by 99er-gao** [comment]
收到，十分感谢您的回复。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月20日 00:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [pmj110119/RenderOcc] 复现问题 (Issue #10) |

把脚本 tools/dist_train.sh 的倒数第二行 --seed 0 \ 去掉，loss看着就正常了（还没训完，等训完出评测结果后我会更新）。

这个随机种子我是从别的repo代码直接复制过来的，不知道为啥加个随机种子模型就不收敛了。有没有大佬解惑一下......

**Comment by 15757955216** [comment]
感谢回复！我尝试了一下去掉随机种子，但是好像仍没有正常收敛(与您的log)比较，是因为会有随机性问题吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pmj110119 ***@***.***&gt;
发送时间: 2023年10月20日 00:19
收件人: pmj110119/RenderOcc ***@***.***&gt;
抄送: H.Y.shu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [pmj110119/RenderOcc] 复现问题 (Issue #10)





 
把脚本 tools/dist_train.sh 的倒数第二行 --seed 0 \ 去掉，loss看着就正常了（还没训完，等训完出评测结果后我会更新）。
 
这个随机种子我是从别的repo代码直接复制过来的，不知道为啥加个随机种子模型就不收敛了。有没有大佬解惑一下......

**Comment by pmj110119** [comment]
已修复，确实有一个小bug（生成rays时xy坐标搞反了），请参照新的commit进行修改～

非常感谢您的问题反馈！！！

**Comment by 15757955216** [comment]
收到。感谢回复！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pmj110119 ***@***.***&gt;
发送时间: 2023年10月21日 02:07
收件人: pmj110119/RenderOcc ***@***.***&gt;
抄送: H.Y.shu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [pmj110119/RenderOcc] 复现问题 (Issue #10)





 
已修复，确实有一个小bug（生成rays时xy坐标搞反了），请参照新的commit进行修改～
