### ISSUE TITLE
visualization video

### ISSUE THREAD

**Issue by zhangbo666666** [pmj110119/RenderOcc#11]
Hello author, thank you for your excellent work. Can the visualization video code tool be open source?

**Comment by pmj110119** [comment]
Thank you for your attention. 

We will update the visualization code soon.

**Comment by samernanoxx** [comment]
Hi, Would you guys publish the visualization script anytime soon? Thanks!

**Comment by abualhanud** [comment]
Hi guys, are you planing to publish the visualization script anytime soon?

**Comment by pmj110119** [comment]
> Hi guys, are you planing to publish the visualization script anytime soon?

Sorry for late reply，I expect an update in 1-2 weeks.

**Comment by pmj110119** [comment]
Apologies for the delay, the visualization code has now been released.

**Comment by pmj110119** [comment]
> Hi guys, are you planing to publish the visualization script anytime soon?

Apologies for the delay, the visualization code has now been released.

**Comment by pmj110119** [comment]
> > Hi guys, are you planing to publish the visualization script anytime soon?
> 
> Sorry for late reply，I expect an update in 1-2 weeks.

Apologies for the delay, the visualization code has now been released.
