### ISSUE TITLE
迁移复现问题

### ISSUE THREAD

**Issue by zhangbo666666** [pmj110119/RenderOcc#12]
作者您好，感谢您出色的工作。有两个问题想请教您~
1、目前我们项目车上只有四个鱼眼相机，没有激光雷达点云数据提供真值生成或者训练监督，请问下您我们是否可以利用离线动态场景下SFM或者动态深度估计获取2D Depth labels + 自标语义分割标注来复现您的工作呢？如果可以的话，您感觉这样的效果会怎么样？
2、基于四个鱼眼相机的纯视觉occupancy network工作您有相关推荐吗？
非常非常感谢，希望能得到您的回复~

**Comment by pmj110119** [comment]
1. In the final section of the [paper](https://arxiv.org/abs/2309.09502)'s **Ablation Study**, we attempt to train the model using 2D depth labels generated by **SFM**. There is a 2~3 mIoU performance drop compared to using LiDAR GT. If you have sufficient data, I think it's worth a try.

2. I'm sorry, I haven't paid attention to occupancy with fisheye cameras.

**Comment by zhangbo666666** [comment]
> 1. In the final section of the [paper](https://arxiv.org/abs/2309.09502)'s **Ablation Study**, we attempt to train the model using 2D depth labels generated by **SFM**. There is a 2~3 mIoU performance drop compared to using LiDAR GT. If you have sufficient data, I think it's worth a try.
> 2. I'm sorry, I haven't paid attention to occupancy with fisheye cameras.

感谢您的回答，想请教大佬一下，我这边只有视觉环视图片数据和2D深度标签真值，在评价求解mIoU的时候需要手动生成3D 占有预测真值来做吗？具体该怎么生成真值呢，希望能得到您的指点~

**Comment by pmj110119** [comment]
1. 用depth和语义真值生成带语义的3D伪点云，接着使用和lidar制作occ GT一样的pipeline制作3D Occ GT（pipeline可以参考[SurroundOcc](https://github.com/weiyithu/SurroundOcc)的代码）。

2. 不直接评测3D Occ mIoU，对渲染出的2D depth/segmentation做间接的评测。（结合可视化）

我感觉只有这两种方式......  第一种如果你们深度真值不是太稀疏的话可以试试？

**Comment by zhangbo666666** [comment]
> 1. 用depth和语义真值生成带语义的3D伪点云，接着使用和lidar制作occ GT一样的pipeline制作3D Occ GT（pipeline可以参考[SurroundOcc](https://github.com/weiyithu/SurroundOcc)的代码）。
> 2. 不直接评测3D Occ mIoU，对渲染出的2D depth/segmentation做间接的评测。（结合可视化）
> 
> 我感觉只有这两种方式...... 第一种如果你们深度真值不是太稀疏的话可以试试？

大致明白了，非常感谢您的耐心解答，谢谢~
