### ISSUE TITLE
dataset organization

### ISSUE THREAD

**Issue by finninmunich** [pmj110119/RenderOcc#13]
Hello!

First of all, thanks for your excellent work!

I have a question about the preparation of dataset. 

In step 1, we need to download the full NuScenes Dataset. I think I need to download the "lidarseg" part also, don't I?

Because I ran into "lidarseg" not found issue when I tried to run python tools/gen_data/gen_seg_gt_from_lidarseg.py.

So I assume I need to download the lidarseg part also. But here is another question: after we download the lidarseg file, inside the lidarseg folder, we have "v1.0-trainval, v1.0-test,v1.0-mini", outside the folder we also have "v1.0-trainval, v1.0-test,v1.0-mini". The outside "v1.0" contains only two files "category.json and lidarseg.json". Do I need to add/overwrite these two files into the original NuScenes folder?

**Comment by pmj110119** [comment]
Yes, you need to download the "lidarseg" data part. This point was inadvertently omitted from our current document. 

Please refer to the file structure below:
```
└── nuscenes  
    ├── Usual nuscenes folders (i.e. samples, sweep)
    │
    ├── lidarseg
    │   └── v1.0-{mini, test, trainval} <- Contains the .bin files; a .bin file 
    │                                      contains the labels of the points in a 
    │                                      point cloud (note that v1.0-test does not 
    │                                      have any .bin files associated with it)
    │
    └── v1.0-{mini, test, trainval}
        ├── Usual files (e.g. attribute.json, calibrated_sensor.json etc.)
        ├── lidarseg.json  <- contains the mapping of each .bin file to the token
        └── category.json  <- contains the categories of the labels (note that the 
                              category.json from nuScenes v1.0 is overwritten)
```
