### ISSUE TITLE
cuda memory

### ISSUE THREAD

**Issue by Yzichen** [pmj110119/RenderOcc#16]
Why does the cuda memory footprint keep changing during training.

**Comment by pmj110119** [comment]
Sorry, I haven't encountered this problem before.

**Comment by chenzyhust** [comment]
> Why does the cuda memory footprint keep changing during training.
注释掉lru_cache就可以了，不然服务器内存不够会爆掉
# @functools.lru_cache(maxsize=32)
def create_full_step_id(shape):
