### ISSUE TITLE
About sparse depth supervision

### ISSUE THREAD

**Issue by eliliu2233** [pmj110119/RenderOcc#17]
Thanks for your exciting work! I'm learning outdoor reconstruction recently and I'm really interested in the conclusions in your paper that           only use sparse depth labels can helps accurate neural rendering results. Since the lidar points is really sparse in Nuscenes,  I think it may cause inaccurate depth estimation in areas without depth supervision, and cause inaccurate occupancy prediction. Meanwhile, sfm results must be much more sparse,  espacially in outdoor scenes. Could you please give me some suggestions to avoid these problems?

**Comment by pmj110119** [comment]
Thanks for your attention! The sparsity of depth GT does lead to model deficiencies. Maybe you can try dense supervision ways such as RGB and unsupervised depth estimation.

By the way, if you have something want to discuss in detail, you can add my social media account.

**Comment by eliliu2233** [comment]
Ok.Thanks for your patient reply.

**Comment by eliliu2233** [comment]
> Thanks for your attention! The sparsity of depth GT does lead to model deficiencies. Maybe you can try dense supervision ways such as RGB and unsupervised depth estimation.
> 
> By the way, if you have something want to discuss in detail, you can add my social media account.

Ok.Thanks for your patient reply.

**Comment by 15757955216** [comment]
I have tried to use multiframe lidar points in generating a denser depth GT. But it doesn't work well exectly. Sometimes it lead to a wrong depth.

**Comment by eliliu2233** [comment]
> I have tried to use multiframe lidar points in generating a denser depth GT. But it doesn't work well exectly. Sometimes it lead to a wrong depth.

hello，can I take a look of your depth rendering results?

**Comment by 15757955216** [comment]
> > I have tried to use multiframe lidar points in generating a denser depth GT. But it doesn't work well exectly. Sometimes it lead to a wrong depth.
> 
> hello，can I take a look of your depth rendering results?

![366025ef-e72c-4d21-8a4e-45b56dc4ecf8](https://github.com/pmj110119/RenderOcc/assets/37320731/53c88e2c-84d8-4456-b601-0fc91991710f)
The single points Vs. multiframe points.

**Comment by eliliu2233** [comment]
> > > I have tried to use multiframe lidar points in generating a denser depth GT. But it doesn't work well exectly. Sometimes it lead to a wrong depth.
> > 
> > 
> > hello，can I take a look of your depth rendering results?
> 
> ![366025ef-e72c-4d21-8a4e-45b56dc4ecf8](https://user-images.githubusercontent.com/37320731/283364505-53c88e2c-84d8-4456-b601-0fc91991710f.png) The single points Vs. multiframe points.

I think it may be a common result caused by occlusion or transparent objects.

**Comment by supremeccccc** [comment]
Hi, I am concerned about the 2d rendering results of the renderocc. Do you have some rendered depth pictures? Thanks.
