### ISSUE TITLE
about 2D depth groundtruth

### ISSUE THREAD

**Issue by windkiss5** [pmj110119/RenderOcc#25]
```
type='Collect3D',
        keys=[
            'img_inputs', 'gt_depth', 'voxel_semantics', 'mask_lidar',
            'mask_camera', 'gt_depths', 'rays'
        ])
```

Thank you very much, author, for your work! Benefiting greatly

I mainly focus on 'gt_depth' and 'gt_depths' has raised questions.

The former is calculated in pipeline
```
@PIPELINES.register_ Module()
Class PointToMultiViewDepth (object):
```

The latter is achieved through "./data/nuscenes/depth_gt"

But upon checking the code, it was found that the source code in the main branch used the former 'gt_depth' there any difference between the two methods of reading the true value of depth?

---------------------
很感谢作者你们的工作！受益匪浅
我主要对'gt_depth'和 'gt_depths'产生了疑问。
前者是在pipline中进行计算的
@PIPELINES.register_module()
class PointToMultiViewDepth(object):

后者是通过./data/nuscenes/depth_gt中的文件获得的

但是检查代码发现main分支中的源码使用的前者'gt_depth'读取的深度真值，请问这两种方式有什么不同么？

**Comment by pmj110119** [comment]
`'depth_gts'` has not been utilized, this is a residual issue in the code. Thank you for pointing it out!


For rendering depth supervision, the labels are generated in the [NuScenesDatasetOccpancy](https://github.com/pmj110119/RenderOcc/blob/09ce2cda6e7b92af86faaaa3984cff837c235625/mmdet3d/datasets/nuscenes_dataset_occ.py#L121C17-L121C82) and employed [here](https://github.com/pmj110119/RenderOcc/blob/09ce2cda6e7b92af86faaaa3984cff837c235625/mmdet3d/datasets/ray.py#L83C23-L83C23).



`'depth_gt'` undergoes image-level augmentation and serves as the **depth label for[ supervising the 2D depth map predictions of LSS](https://github.com/pmj110119/RenderOcc/blob/09ce2cda6e7b92af86faaaa3984cff837c235625/mmdet3d/models/detectors/render_occ.py#L157)** (part of the BEVStereo-Baseline). 
If you are using a different network architecture, such as Former-based models, this depth supervision is not required.
