### ISSUE TITLE
I can not download gts files from your link projection, could you share your link of gts

### ISSUE THREAD

**Issue by HenryZhangJianhe** [pmj110119/RenderOcc#28]
FoundError: [Errno 2] No such file or directory:  ./data/nuscenes/gts/scene-0738/e412cd15abe94867b568e8c4ae4d1036/labels.npz

**Comment by HenryZhangJianhe** [comment]
![image](https://github.com/pmj110119/RenderOcc/assets/52202915/10b8e583-b49d-4c3a-afd3-b66c54beb9f3)
或者如何设置不用这个gts呢?

**Comment by pmj110119** [comment]
You can download `gts` from[ here](https://drive.google.com/drive/folders/1Xarc91cNCNN3h8Vum-REbI-f0UlSf5Fc)
