### ISSUE TITLE
test_pipeline did not include key “gt_semantics“

### ISSUE THREAD

**Issue by HenryZhangJianhe** [pmj110119/RenderOcc#29]
self.keys : 
 ['points', 'img_inputs', 'voxel_semantics', 'mask_lidar', 'mask_camera', 'gt_depths', ' gt_semantics', 'rays']
data.keys(): 
 dict_keys(['img_metas'])

result.kesy() : 
 dict_keys(['sample_idx', 'pts_filename', 'sweeps', 'timestamp', 'ann_infos', 'curr', 'adjacent', 'with_gt', 'occ_gt_path', 'rays', 'img_fields', 'bbox3d_fields', 'pts_mask_fields', 'pts_seg_fields', 'bbox_fields', 'mask_fields', 'seg_fields', 'box_type_3d', 'box_mode_3d', 'cam_names', 'canvas', 'img_inputs', 'gt_depths', 'voxel_semantics', 'mask_lidar', 'mask_camera', 'gt_bboxes_3d', 'gt_labels_3d', 'flip_dx', 'flip_dy', 'points', 'scale', 'flip', 'pcd_scale_factor', 'flip_direction', 'pcd_horizontal_flip', 'pcd_vertical_flip'])

**Comment by pmj110119** [comment]
Thanks for report!!!!!!   The bug has been fixed.
