### ISSUE TITLE
The mIoU of Uniocc and RenderOcc is not same

### ISSUE THREAD

**Issue by HenryZhangJianhe** [pmj110119/RenderOcc#30]
Uniocc CVPR2023-3D-Occupancy-Prediction nuscenes  is 51.27
RenderOcc occ3d-nuscens 26.11
是因为这两个测试数据集的gt 差别很大导致性能差别很大？
![image](https://github.com/pmj110119/RenderOcc/assets/52202915/809dbccc-05c2-4634-84c2-45c75853d4ad)

![image](https://github.com/pmj110119/RenderOcc/assets/52202915/0a79af59-a9c3-4385-b954-6736525881fc)

**Comment by pmj110119** [comment]
The former score is based on the use of `camera_mask` during training, which can bring huge improvement to the metric, but the visualization result will become worse. **This is explained in Section 2.4 of UniOcc.**

In the CVPR2023 Challenge that UniOcc participated in, `camera_mask` was allowed to be used by the organizer. However, the use of this mask is controversial for research, and I recommend following the [Occ3D](https://arxiv.org/abs/2304.14365) paper and not using it.

**Comment by 99er-gao** [comment]
@pmj110119 Hello author, thank you for your excellent work. In Section 2.4, it is mentioned that "employee mask camera for loss during training". May I ask if mask_camera is only used in loss_3d? If it is also used in loss_rendering, how is it utilized? I am very confused and looking forward to your reply. Thank you!

**Comment by pmj110119** [comment]
> @pmj110119 Hello author, thank you for your excellent work. In Section 2.4, it is mentioned that "employee mask camera for loss during training". May I ask if mask_camera is only used in loss_3d? If it is also used in loss_rendering, how is it utilized? I am very confused and looking forward to your reply. Thank you!

Yes, `mask_camera` can only be used for loss_3d.
