### ISSUE TITLE
Occ GT and prediction

### ISSUE THREAD

**Issue by abualhanud** [pmj110119/RenderOcc#32]
Hi,

Did you notice that the drivable surface in the prediction is a bit higher than the GT. Do you have a theory on what might be the reason.

![Screenshot 2024-02-03 181922](https://github.com/pmj110119/RenderOcc/assets/106312980/cda13181-690c-44b5-90ed-6b4a8cd66d78)
[img from RenderOcc paper]

**Comment by pmj110119** [comment]
This could be attributed to the model's lack of precision in predicting edge regions.
