### ISSUE TITLE
Details of NerfHead parameters

### ISSUE THREAD

**Issue by yutao98** [pmj110119/RenderOcc#35]
Hi, when i change nerfhead config to a smaller version, i cant get expected rendering results. Config has been modified according to #20.
Could you give some suggestion or more explaination of paremeters in NerfHead?
Here is my config. 
```    
model = dict(
    type='RenderOcc',
    final_softplus=True,
    nerf_head=dict(
        type='NerfHead',
        point_cloud_range=[-51.2, -51.2, -1.0, 51.2, 51.2, 5.0],
        voxel_size=1.6,
        step_size=1.6,
        scene_center=[0, 0, 2.0],
        world_size=[64,64,4],
        radius=50,
        use_depth_sup=True,
```
By the way, 
https://github.com/pmj110119/RenderOcc/blob/446b7fd315cb98ff084d90058ff90cbe59bfe91e/mmdet3d/models/nerf/nerf_head.py#L218
I modified this line to:
`alpha = self.activate_density(density, interval=self.step_size)`
Is that right?

**Comment by pmj110119** [comment]
Yes, it's right.
