### ISSUE TITLE
Results of RenderOcc and UniOcc paper

### ISSUE THREAD

**Issue by OrangeSodahub** [pmj110119/RenderOcc#39]
Hi, I notice that the results shown in RenderOcc(https://arxiv.org/pdf/2309.09502.pdf) and UniOcc(https://arxiv.org/pdf/2306.09117.pdf) are different, which are 26.11 (TABLE 1) and 52.1 (TALBLE 1). Well I simply check the dataset you used (challenge dataset and occ3d-nuscenes), I feel that these two dataset are the same one right? So why the two results are so different? Thanks!

**Comment by pmj110119** [comment]
Hi, that's because the usage of `mask_camera` during UniOcc's training, which is controversial for research. You can refer to [issue#30 ](https://github.com/pmj110119/RenderOcc/issues/30).
