### ISSUE TITLE
Output dimension of density mlp

### ISSUE THREAD

**Issue by OrangeSodahub** [pmj110119/RenderOcc#40]
I was wondering why here outputs 2 dimension and only one is used:

https://github.com/pmj110119/RenderOcc/blob/446b7fd315cb98ff084d90058ff90cbe59bfe91e/mmdet3d/models/detectors/render_occ.py#L141-L142

Did you consider that the first dimension represents the empty and another reprensets the non-empty?

**Comment by pmj110119** [comment]
Your guess is correct. This is to use 2D rendering loss and 3D classification loss at the same time. But if you don’t use 3D loss, you can only use one channel

**Comment by OrangeSodahub** [comment]
@pmj110119 The second `softplus` here is actually the activation of density field like other nerf works do?

https://github.com/pmj110119/RenderOcc/blob/446b7fd315cb98ff084d90058ff90cbe59bfe91e/mmdet3d/models/detectors/render_occ.py#L57-L62

**Comment by pmj110119** [comment]
> @pmj110119 The second `softplus` here is actually the activation of density field like other nerf works do?↳
> 
> https://github.com/pmj110119/RenderOcc/blob/446b7fd315cb98ff084d90058ff90cbe59bfe91e/mmdet3d/models/detectors/render_occ.py#L57-L62

Yes

**Comment by OrangeSodahub** [comment]
And if I need to use `mask_camera`, do I need to transpose the h and w dimension? Thanks

https://github.com/pmj110119/RenderOcc/blob/446b7fd315cb98ff084d90058ff90cbe59bfe91e/mmdet3d/models/detectors/render_occ.py#L80-L96

```
mask_camera = mask_camera.permute(0, 2, 1, 3) # whether or not?
mask_camera = mask_camera.reshape(-1)
```

**Comment by OrangeSodahub** [comment]
@pmj110119 Thanks! And if I need to use `mask_camera`, do I need to transpose the h and w dimension? Thanks

https://github.com/pmj110119/RenderOcc/blob/446b7fd315cb98ff084d90058ff90cbe59bfe91e/mmdet3d/models/detectors/render_occ.py#L80-L96
