### ISSUE TITLE
Using Nuscenes Dataset

### ISSUE THREAD

**Issue by Shiyao-Xu** [pmj110119/RenderOcc#41]
Hello RenderOcc Team,

thank you for your excellent work! I have a question regarding choice of dataset. I noticed that you mentioned the shortcomings of Semantic-KITTI in the "Experiment" part of the paper. I would like to ask do you consider to support Nuscenes dataset in the future?

Thank you for your time!

Best Regards,
Shiyao

**Comment by pmj110119** [comment]
Hi Shiyao,

This repo already supports nuscenes.

**Comment by Shiyao-Xu** [comment]
Ah right, I'm fool:))
