### ISSUE TITLE
Question aboud dynamic class

### ISSUE THREAD

**Issue by jimchenhub** [pmj110119/RenderOcc#43]
Thanks for you work. I have a question about the setting of dynamic class.
In your code, dynamic classes are
```
dynamic_class = [0, 1, 3, 4, 5, 7, 9, 10]
```
According to the label mapping as below, that means `noise` and `barrier` are dynamic classes and `bicycle` and `motorcycle` are not dynamic classes. This setting seems a bit unreasonable. What is the reason for this setting?
```
label_map = {
    'animal':0, 
    'human.pedestrian.personal_mobility':0, 
    'human.pedestrian.stroller':0, 
    'human.pedestrian.wheelchair':0, 
    'movable_object.debris':0,
    'movable_object.pushable_pullable':0, 
    'static_object.bicycle_rack':0, 
    'vehicle.emergency.ambulance':0, 
    'vehicle.emergency.police':0, 
    'noise':0, 
    'static.other':0, 
    'vehicle.ego':0,
    'movable_object.barrier':1, 
    'vehicle.bicycle':2,
    'vehicle.bus.bendy':3,
    'vehicle.bus.rigid':3,
    'vehicle.car':4,
    'vehicle.construction':5,
    'vehicle.motorcycle':6,
    'human.pedestrian.adult':7,
    'human.pedestrian.child':7,
    'human.pedestrian.construction_worker':7,
    'human.pedestrian.police_officer':7,
    'movable_object.trafficcone':8,
    'vehicle.trailer':9,
    'vehicle.truck':10,
    'flat.driveable_surface':11,
    'flat.other':12,
    'flat.sidewalk':13,
    'flat.terrain':14,
    'static.manmade':15,
    'static.vegetation':16
}
```

**Comment by pmj110119** [comment]
Thanks for pointing it out. 

It's been a while, but I remember that the reason for this setting is that in the nuscenes dataset, most of bicycles and motorcycles are "parked" on the roadside, so I classified them as static objects.

**Comment by jimchenhub** [comment]
Thanks for your quick reply. Parked bicycles seem reasonable as static class. But the `barrier` are generally not move.
To make an accurate labeling, it might be a good choice to use the original categories of LiDAR point.

**Comment by pmj110119** [comment]
Yes, what you said is a more reasonable way.
