### ISSUE TITLE
Depth supervision experiment

### ISSUE THREAD

**Issue by rmarcuzzi** [pmj110119/RenderOcc#45]
Hi!
Thanks for sharing your code and congrats on the nice work!
I have a question regarding the ablation study in Table V: analysis of depth supervision. 
* In the first row you don't use depth supervision. How did you perform this experiment? How did you sample the rays? Where did you get the semantics from?
* In the third row you use the pseudo-labels derived from SurroundDepth which are quite sparse. Here as well, did you change something in the training? Where did you get the semantics from?

Thank you in advance!

**Comment by pmj110119** [comment]
Hi, in our main experiment, we used lidarseg data to sample rays and obtain their corresponding depth/semantic labels. The experiments in Table V were modified based on the main experiment as follows:

1. In the first row, ray sampling and semantic supervision were kept unchanged, but **depth loss was directly disabled**.
2. In the third row, we **additionally sampled some rays** and their corresponding depth labels obtained through SurroundDepth into the first row of experiments to compute the depth loss.

**Comment by rmarcuzzi** [comment]
Hi! Thanks for the quick and complete response, it clarifies the experimental setup.
I understand now that you always used the semantic GT and that in the third row, you kept the original "lidar rays" for semantic supervision and added some more (corresponding to the depth labels) for depth supervision.
Thanks!
