### ISSUE TITLE
How to build the continuous SDF by predicted voxel-wise density and semantic?

### ISSUE THREAD

**Issue by perisage** [pmj110119/RenderOcc#6]
The volume feature map  input to density mlp and semantic mlp is converted to voxel-wise density and semantic. But in the rendering process, use continuous density and semantic fields for any viewpoint render. So  how do you build the continuous fields by the voxel-wise density and semantics?  Thanks!

**Comment by pmj110119** [comment]
Sorry for the late reply. 

Through interpolation, specifically using the bilinear mode of **F.grid_sample()**.

**Comment by perisage** [comment]
Got it! Thanks for your reply.
