### ISSUE TITLE
How about generate rays directly from lidarseg

### ISSUE THREAD

**Issue by secret104278** [pmj110119/RenderOcc#7]
Hi teams,
Currently, the ground truth generation pipeline is to project lidar data to each camera and generate 2D depth and segmentation input as Nerf rendering target. However, I'm curious that have you try to use lidar as the nerf ray directly (for example, ray_o is at lidar sensor position), and and experiment on which method will provider better result?

**Comment by pmj110119** [comment]
Yes, it is possible to directly use LiDAR points to generate rays. This approach avoids the numerical errors associated with 2D projection and can yield slight performance improvements (we compared this in early experiments). 

As the main focus of the paper is to train models using 2D image labels,  which are not provided by NuScenes, we had to generate 2D image labels by projecting lidarseg. If your project does not have this constraint, you can certainly use LiDAR points to generate rays directly.

**Comment by secret104278** [comment]
Hi @pmj110119, thanks for your insight. Besides, it is possible for you to open source the lidar ray version of your early experiments?

**Comment by pmj110119** [comment]
I'm sorry, that experiment is too early-stage and significantly different from the current released version. Implementing 'lidar ray' directly in the current version's code is a more cost-effective way. 

If I have the time in the future, I may attempt to add this option, but it's not on the immediate roadmap. 
(If you're willing, I would greatly welcome you to submit a pull request.)
