### ISSUE TITLE
Regarding the question of how to obtain "occ_infos_temporal_val.pkl"

### ISSUE THREAD

**Issue by KarlLi5** [pmj110119/RenderOcc#9]
Hello, when I was preparing the dataset, I ran the "tools/gen_data/gen_seg_gt_from_lidarseg.py" file as instructed in the readme, and it prompted a missing "occ_infos_temporal_val.pkl" file. However, I haven't found any information elsewhere on how to obtain or generate this .pkl file.

**Comment by pmj110119** [comment]
I apologize for placing the script in the wrong location. 

Please use 
```
python tools/gen_seg_gt_from_lidarseg.py
```
 instead of 
```
python tools/gen_data/gen_seg_gt_from_lidarseg.py
```

You can also opt to pull the latest code; I have fixed this issue in the latest commit.

**Comment by KarlLi5** [comment]
> I apologize for placing the script in the wrong location.
> 
> Please use
> 
> ```
> python tools/gen_seg_gt_from_lidarseg.py
> ```
> 
> instead of
> 
> ```
> python tools/gen_data/gen_seg_gt_from_lidarseg.py
> ```
> 
> You can also opt to pull the latest code; I have fixed this issue in the latest commit.

您好，我按照你说的运行另一个gen_seg_gt_from_lidarseg.py文件，但是在运行203行的时候会出现报错[AssertionError: Table lidarseg not found]，我从nuscenes上官网下载了完整的lidarseg文件放到了data/nuscenes下，但是还是依然报错，找不到解决方法，无法完成gt生成

**Comment by pmj110119** [comment]
应该还是路径问题，是不是没有放置lidarseg.json文件？

可以参考下NuScenes官方文档中的文件结构：https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/nuscenes_lidarseg_panoptic_tutorial.ipynb
